name: Auto Merge Between Branches

on:
  push:
    branches:
      - dev
      - staging

jobs:
  merge-branches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

      - name: Merge dev → staging
        if: github.ref == 'refs/heads/dev'
        run: |
          git checkout staging || git checkout -b staging
          git merge dev --no-edit
          git push origin staging

      - name: Merge staging → main
        if: github.ref == 'refs/heads/staging'
        run: |
          git checkout main || git checkout -b main
          git merge staging --no-edit
          git push origin main
