name: Push to Main - Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  docker-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push backend image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ml-backend ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/ml-backend

      - name: Build and push frontend image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ml-frontend ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/ml-frontend